#cloud-config
users: #Ist um benutzer zu erstellen
  - name: ubuntu #Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin #Gruppen des Users
    home: /home/ubuntu #Home-Verzeichnis des Users
    shell: /bin/bash #der Pfad zur shell
    ssh_authorized_keys: #Public Key
      - ssh-rsa MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv06L4EcXZfdlyLKhdvbD+/O6yiUgsT0pbPwKe5ON8pb/Ejt/Mi/4++J4n/Kr1MsNVI+1H5QyicF86tvpVYLnQmbaphoXO+4XWdrvWSfXh7pPJKB1L1DJQHI71zlSnNb35a00Orq0VsY0MIHKT617Wzy26reKqj2mYdQn59NXrJwtZrKPnAl4eRusPrm3ZFljH37R6OD0eaSr7BhBFKyd31wKmcf6ozEOO+3NVEVEgr0pwO3HbtkuLlU6I9LA8c7VxLNubZoKIEi5McCdwC+O2QFXVYrOF6idDolKmiKwHfbRsgFiiOivqNGiVM4oN9iEnjwFuE21RQsbEkz1GJTeDQIDAQAB aws-key       
ssh_pwauth: false #Deaktiviert die Verwendung von Passwörtern bei SSH
disable_root: false #Man kann sich nicht mehr als root anmelden
package_update: true #Macht ein update der Paketlisten
packages: #Packages die installiert werden
  - curl 
  - wget 
